[package]
name = "pmr_shukusei_lolikami_requiem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
rascii_art = "0.4.5"
rayon = "1.8.0"
